# Generated by Django 3.2 on 2022-07-14 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[shop.validators.point_validator]),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop.product'),
        ),
    ]
