# Generated by Django 3.2 on 2022-11-24 04:54

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('alt', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='uploads/', validators=[shop.validators.validate_minimum_size]),
        ),
    ]
