# Generated by Django 3.2 on 2022-11-30 06:04

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221127_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state_payment',
            field=models.IntegerField(blank=True, choices=[(1, 'new'), (2, 'pending'), (3, 'payment approved'), (4, 'admin checking'), (5, 'admin failed'), (6, 'payment failed')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='uploads/', validators=[shop.validators.validate_minimum_size]),
        ),
    ]
