# Generated by Django 3.2 on 2022-12-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221123_2106'),
        ('shop', '0006_auto_20221129_2204'),
    ]

    operations = [
    ]
