# Generated by Django 3.2 on 2022-12-25 18:32

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='uploads/', validators=[shop.validators.validate_minimum_size]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state_payment',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'pending'), (3, 'payment approved'), (4, 'admin checking'), (5, 'admin failed'), (6, 'payment failed')]),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
